In [1]:
import pandas as pd
import ast

In [2]:
# Cargo el dataset de credits
dfc = pd.read_csv('../credits.csv')

In [3]:
dfc.head(3)

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602

In [4]:
# Creo una columna a que llamo actores
dfc['actores'] = ''

In [5]:
# Creo una funcion para extraer todos los actores de la columna cast y grabarlo en una nueva columna llamada 'Actors'
for index in dfc['cast'].index:
    lista_diccionarios = ast.literal_eval(dfc['cast'][index])
    actors = []
    for dict in lista_diccionarios:
        for key, value in dict.items():
            if key == 'name':
                actors.append(value)
    dfc.at[index, 'actores'] = actors

In [6]:
#Verifico la carga correcta de actores en la nueva columna
dfc['actores']

0        [Tom Hanks, Tim Allen, Don Rickles, Jim Varney...
1        [Robin Williams, Jonathan Hyde, Kirsten Dunst,...
2        [Walter Matthau, Jack Lemmon, Ann-Margret, Sop...
3        [Whitney Houston, Angela Bassett, Loretta Devi...
4        [Steve Martin, Diane Keaton, Martin Short, Kim...
                               ...
45471          [Leila Hatami, Kourosh Tahami, Elham Korda]
45472    [Angel Aquino, Perry Dizon, Hazel Orencio, Joe...
45473    [Erika Eleniak, Adam Baldwin, Julie du Page, J...
45474    [Iwan Mosschuchin, Nathalie Lissenko, Pavel Pa...
45475                                                   []
Name: actores, Length: 45476, dtype: object

In [7]:
#Verifico el funcionamiento correcto de la busqueda de actores con el nombre Tom Cruise mediante la funcion lambda
result_actor = dfc.loc[dfc['actores'].apply(lambda x: 'Tom Cruise' in x)]

In [8]:
result_actor

,cast,crew,id,actores
249,"[{'cast_id': 18, 'character': 'Louis de Pointe...","[{'credit_id': '52fe4260c3a36847f8019995', 'de...",628,"[Brad Pitt, Tom Cruise, Kirsten Dunst, Antonio..."
449,"[{'cast_id': 13, 'character': 'Mitch McDeere',...","[{'credit_id': '52fe46359251416c9104ceef', 'de...",37233,"[Tom Cruise, Jeanne Tripplehorn, Gene Hackman,..."
638,"[{'cast_id': 22, 'character': 'Ethan Hunt', 'c...","[{'credit_id': '52fe4292c3a36847f8029493', 'de...",954,"[Tom Cruise, Jon Voight, Emmanuelle Béart, Hen..."
1068,"[{'cast_id': 19, 'character': 'Cole Trickle', ...","[{'credit_id': '52fe4337c3a36847f80434fd', 'de...",2119,"[Tom Cruise, Robert Duvall, Nicole Kidman, Ran..."
1069,"[{'cast_id': 13, 'character': ""Pete 'Maverick'...","[{'credit_id': '52fe426fc3a36847f801e685', 'de...",744,"[Tom Cruise, Kelly McGillis, Val Kilmer, Antho..."
1329,"[{'cast_id': 11, 'character': ""William H. 'Bil...","[{'credit_id': '52fe44ab9251416c7503ce87', 'de...",11967,"[Emilio Estevez, Kiefer Sutherland, Lou Diamon..."
1344,"[{'cast_id': 1, 'character': 'Jerry Maguire', ...","[{'credit_id': '52fe44f1c3a36847f80b33c7', 'de...",9390,"[Tom Cruise, Cuba Gooding Jr., Renée Zellweger..."
1852,"[{'cast_id': 4, 'character': 'Raymond Babbitt'...","[{'credit_id': '52fe423cc3a36847f800e92d', 'de...",380,"[Dustin Hoffman, Tom Cruise, Valeria Golino, G..."
2005,"[{'cast_id': 11, 'character': ""Dallas 'Dally' ...","[{'credit_id': '52fe4229c3a36847f8008b9b', 'de...",227,"[Matt Dillon, Ralph Macchio, C. Thomas Howell,..."
2034,"[{'cast_id': 9, 'character': 'Jack', 'credit_i...","[{'credit_id': '52fe44ae9251416c7503d3cb', 'de...",11976,"[Tom Cruise, Mia Sara, Tim Curry, David Bennen..."
2156,"[{'cast_id': 10, 'character': 'Lt. Daniel Kaff...","[{'credit_id': '52fe4286c3a36847f8025d91', 'de...",881,"[Tom Cruise, Jack Nicholson, Demi Moore, Kevin..."
2361,"[{'cast_id': 7, 'character': 'Fast Eddie Felso...","[{'credit_id': '52fe44979251416c7503a3ad', 'de...",11873,"[Paul Newman, Tom Cruise, Mary Elizabeth Mastr..."
2597,"[{'cast_id': 1, 'character': ""Dr. William 'Bil...","[{'credit_id': '52fe423bc3a36847f800df81', 'de...",345,"[Tom Cruise, Nicole Kidman, Madison Eginton, J..."
2799,"[{'cast_id': 1, 'character': 'Joel Goodsen', '...","[{'credit_id': '52fe44ebc3a36847f80b1c5d', 'de...",9346,"[Tom Cruise, Rebecca De Mornay, Sean Penn, Joe..."
3043,"[{'cast_id': 3, 'character': 'Linda Partridge'...","[{'credit_id': '52fe4239c3a36847f800d677', 'de...",334,"[Julianne Moore, William H. Macy, John C. Reil..."
3141,"[{'cast_id': 10, 'character': 'Joseph Donnelly...","[{'credit_id': '52fe441b9251416c75029157', 'de...",11259,"[Tom Cruise, Nicole Kidman, Thomas Gibson, Rob..."
3501,"[{'cast_id': 31, 'character': 'Ethan Hunt', 'c...","[{'credit_id': '589783759251412e1601cef6', 'de...",955,"[Tom Cruise, Dougray Scott, Thandie Newton, Vi..."
3883,"[{'cast_id': 1, 'character': 'Ron Kovic', 'cre...","[{'credit_id': '52fe435fc3a36847f804f4f5', 'de...",2604,"[Tom Cruise, Raymond J. Barry, Caroline Kava, ..."
4078,"[{'cast_id': 1, 'character': 'Woody', 'credit_...","[{'credit_id': '52fe452e9251416c9102a291', 'de...",33676,"[Tom Cruise, Jackie Earle Haley, John Stockwel..."
4359,"[{'cast_id': 1, 'character': 'Brian Flanagan',...","[{'credit_id': '52fe4482c3a36847f809a5c3', 'de...",7520,"[Tom Cruise, Bryan Brown, Elisabeth Shue, Lisa..."
4845,"[{'cast_id': 13, 'character': 'David Aames', '...","[{'credit_id': '52fe4320c3a36847f803c339', 'de...",1903,"[Tom Cruise, Penélope Cruz, Cameron Diaz, Kurt..."
5092,"[{'cast_id': 1, 'character': 'Stefen Djordjevi...","[{'credit_id': '52fe47659251416c75097d57', 'de...",18172,"[Tom Cruise, Craig T. Nelson, Lea Thompson, Ch..."
5103,"[{'cast_id': 1, 'character': 'General Harlan B...","[{'credit_id': '52fe43979251416c75016725', 'de...",10627,"[George C. Scott, Timothy Hutton, Ronny Cox, S..."
5311,"[{'cast_id': 5, 'character': 'Chief John Ander...","[{'credit_id': '52fe4223c3a36847f8006f3d', 'de...",180,"[Tom Cruise, Colin Farrell, Samantha Morton, M..."
5347,"[{'cast_id': 29, 'character': 'Austin Powers /...","[{'credit_id': '52fe427bc3a36847f80220e9', 'de...",818,"[Mike Myers, Beyoncé Knowles, Seth Green, Mich..."
5592,"[{'cast_id': 2, 'character': 'Jade Butterfield...","[{'credit_id': '5691c92992514115c5000835', 'de...",19114,"[Brooke Shields, Martin Hewitt, Shirley Knight..."
6991,"[{'cast_id': 11, 'character': 'Captain Nathan ...","[{'credit_id': '52fe425ec3a36847f8018e53', 'de...",616,"[Tom Cruise, Ken Watanabe, William Atherton, C..."
8071,"[{'cast_id': 2, 'character': 'Vincent', 'credi...","[{'credit_id': '5811265bc3a368798a00d2e3', 'de...",1538,"[Tom Cruise, Jamie Foxx, Jada Pinkett Smith, M..."
10177,"[{'cast_id': 13, 'character': 'Ray Ferrier', '...","[{'credit_id': '52fe4213c3a36847f8002237', 'de...",74,"[Tom Cruise, Dakota Fanning, Miranda Otto, Jus..."
10952,"[{'cast_id': 23, 'character': 'Ethan Hunt', 'c...","[{'credit_id': '52fe4293c3a36847f8029707', 'de...",956,"[Tom Cruise, Philip Seymour Hoffman, Ving Rham..."
12185,"[{'cast_id': 2, 'character': 'Dr. Stephen Mall...","[{'credit_id': '52fe43c7c3a36847f806f0b1', 'de...",4515,"[Robert Redford, Meryl Streep, Tom Cruise, Mic..."
12883,"[{'cast_id': 2, 'character': 'Tugg Speedman', ...","[{'credit_id': '52fe447dc3a36847f8099323', 'de...",7446,"[Ben Stiller, Jack Black, Robert Downey Jr., N..."
13224,"[{'cast_id': 8, 'character': 'Claus Schenk Gra...","[{'credit_id': '538319b20e0a2657cd004f23', 'de...",2253,"[Tom Cruise, Carice van Houten, Kenneth Branag..."
13665,"[{'cast_id': 1, 'character': 'Narration', 'cre...","[{'credit_id': '52fe44179251416c91004973', 'de...",30416,"[Tom Cruise, Stanley Kubrick, Barbara Kroner, ..."
15487,"[{'cast_id': 3, 'character': 'Roy Miller', 'cr...","[{'credit_id': '563f4ac49251413442006a47', 'de...",37834,"[Tom Cruise, Cameron Diaz, Peter Sarsgaard, Vi..."
18289,"[{'cast_id': 5, 'character': 'Ethan Hunt', 'cr...","[{'credit_id': '53563fb00e0a262861002dd0', 'de...",56292,"[Tom Cruise, Jeremy Renner, Simon Pegg, Paula ..."
19099,"[{'cast_id': 19, 'character': 'Sherrie Christi...","[{'credit_id': '52fe47c99251416c91075afd', 'de...",80585,"[Julianne Hough, Diego Boneta, Tom Cruise, Ale..."
20049,"[{'cast_id': 1001, 'character': 'Jack Reacher'...","[{'credit_id': '52fe4912c3a368484e1191ab', 'de...",75780,"[Tom Cruise, Rosamund Pike, Richard Jenkins, D..."
20470,"[{'cast_id': 1016, 'character': 'Dr. William H...","[{'credit_id': '57c5a0319251412158002832', 'de...",84330,"[Tom Cruise, Jack Nicholson, Stephen King, Nic..."
20749,"[{'cast_id': 1, 'character': 'Jack Harper', 'c...","[{'credit_id': '52fe4909c3a368484e11767f', 'de...",75612,"[Tom Cruise, Morgan Freeman, Olga Kurylenko, A..."
23464,"[{'cast_id': 12, 'character': 'Maj. William ""B...","[{'credit_id': '52fe4c27c3a368484e1aa1cb', 'de...",137113,"[Tom Cruise, Emily Blunt, Brendan Gleeson, Bil..."
23471,"[{'cast_id': 1, 'character': 'Ethan Hunt', 'cr...","[{'credit_id': '550effb5c3a3683e7f002f43', 'de...",177677,"[Tom Cruise, Rebecca Ferguson, Simon Pegg, Jer..."
27854,"[{'cast_id': 10, 'character': 'Himself - Inter...","[{'credit_id': '54beb575c3a368145e00bd4e', 'de...",318224,"[Paul Haggis, Jason Beghe, Alex Gibney, Lawren..."
35269,"[{'cast_id': 2, 'character': 'Himself', 'credi...","[{'credit_id': '540f3a860e0a2627ad000179', 'de...",291537,"[Paul Newman, Tom Cruise, Robert Redford, Joan..."
41064,"[{'cast_id': 0, 'character': 'Jack Reacher', '...","[{'credit_id': '55fdcfa7c3a368133400196b', 'de...",343611,"[Tom Cruise, Cobie Smulders, Aldis Hodge, Dani..."
43248,"[{'cast_id': 7, 'character': 'Nick Morton', 'c...","[{'credit_id': '58b9e962c3a368668f00ced0', 'de...",282035,"[Tom Cruise, Russell Crowe, Annabelle Wallis, ..."
44086,"[{'cast_id': 1, 'character': 'Narrator', 'cred...","[{'credit_id': '5506cacac3a3686b75001d6e', 'de...",18221,"[Tom Cruise, James Arnold, Michael J. Bloomfie..."

In [9]:
# Creo una funcion para extraer todos los directores de la columna crew y grabarlo en una nueva columna llamada 'directors'
for index in dfc['crew'].index:
    lista_diccionarios = ast.literal_eval(dfc['crew'][index])
    found_condition = False
    directors = []
    for dict in lista_diccionarios:
        for key, value in dict.items():
            if found_condition:
                directors.append(value)
                found_condition = False
                break
            if key == 'job' and value == 'Director':
                found_condition = True
    dfc.at[index, 'directores'] = directors

In [10]:
#Verifico la carga correcta de directores en la nueva columna
dfc['directores']

0             John Lasseter
1            [Joe Johnston]
2           [Howard Deutch]
3         [Forest Whitaker]
4           [Charles Shyer]
                ...
45471    [Hamid Nematollah]
45472            [Lav Diaz]
45473      [Mark L. Lester]
45474    [Yakov Protazanov]
45475       [Daisy Asquith]
Name: directores, Length: 45476, dtype: object

In [17]:
#Chequeo el funcionamiento correcto de la busqueda de directores con el nombre Oliver Stone mediante la funcion lambda.
result_director = dfc.loc[dfc['directores'].apply(lambda x: 'Oliver Stone' in x)]

In [18]:
result_director

,cast,crew,id,actores,directores
13,"[{'cast_id': 1, 'character': 'Richard Nixon', ...","[{'credit_id': '52fe43c59251416c7501d6f3', 'de...",10858,"[Anthony Hopkins, Joan Allen, Powers Boothe, E...",[Oliver Stone]
284,"[{'cast_id': 49, 'character': 'Mickey Knox', '...","[{'credit_id': '52fe422bc3a36847f8009679', 'de...",241,"[Woody Harrelson, Juliette Lewis, Robert Downe...",[Oliver Stone]
460,"[{'cast_id': 2, 'character': 'Steve Butler', '...","[{'credit_id': '52fe44929251416c91015565', 'de...",31642,"[Tommy Lee Jones, Robert John Burke, Timothy C...",[Oliver Stone]
1058,"[{'cast_id': 36, 'character': 'Staff Sergeant ...","[{'credit_id': '52fe4277c3a36847f8020cc9', 'de...",792,"[Tom Berenger, Charlie Sheen, Willem Dafoe, Fo...",[Oliver Stone]
1061,"[{'cast_id': 13, 'character': 'Jim Morrison', ...","[{'credit_id': '52fe43839251416c750133f1', 'de...",10537,"[Val Kilmer, Meg Ryan, Kyle MacLachlan, Frank ...",[Oliver Stone]
1553,"[{'cast_id': 11, 'character': 'Bobby Cooper', ...","[{'credit_id': '52fe43379251416c75007dc3', 'de...",10155,"[Sean Penn, Nick Nolte, Jennifer Lopez, Joaqui...",[Oliver Stone]
3056,"[{'cast_id': 16, 'character': ""Tony D'Amato"", ...","[{'credit_id': '56786ed0925141118c000774', 'de...",9563,"[Al Pacino, Cameron Diaz, Dennis Quaid, James ...",[Oliver Stone]
3267,"[{'cast_id': 23, 'character': 'Jim Garrison', ...","[{'credit_id': '52fe427bc3a36847f8022365', 'de...",820,"[Kevin Costner, Tommy Lee Jones, Gary Oldman, ...",[Oliver Stone]
3882,"[{'cast_id': 8, 'character': 'Bud Fox', 'credi...","[{'credit_id': '52fe43a09251416c75017bd9', 'de...",10673,"[Charlie Sheen, Michael Douglas, Martin Sheen,...",[Oliver Stone]
3883,"[{'cast_id': 1, 'character': 'Ron Kovic', 'cre...","[{'credit_id': '52fe435fc3a36847f804f4f5', 'de...",2604,"[Tom Cruise, Raymond J. Barry, Caroline Kava, ...",[Oliver Stone]
3884,"[{'cast_id': 1, 'character': 'Barry Champlain'...","[{'credit_id': '52fe43309251416c75006e47', 'de...",10132,"[Eric Bogosian, Ellen Greene, Leslie Hope, Joh...",[Oliver Stone]
4279,"[{'cast_id': 1, 'character': 'Richard Boyle', ...","[{'credit_id': '52fe443dc3a36847f808a5e1', 'de...",6106,"[James Woods, Jim Belushi, Michael Murphy, Joh...",[Oliver Stone]
5616,"[{'cast_id': 4, 'character': 'Jonathan Lansdal...","[{'credit_id': '52fe45f0c3a36847f80e32bd', 'de...",42149,"[Michael Caine, Andrea Marcovicci, Annie McEnr...",[Oliver Stone]
7851,"[{'cast_id': 3, 'character': 'Himself', 'credi...","[{'credit_id': '5961c635c3a36828a10e4961', 'de...",25783,"[Oliver Stone, Juanita Vera, Fidel Castro, Ern...",[Oliver Stone]
8250,"[{'cast_id': 42, 'character': 'Alexander', 'cr...","[{'credit_id': '53943d0dc3a3684252000c2c', 'de...",1966,"[Colin Farrell, Angelina Jolie, Val Kilmer, Ja...",[Oliver Stone]
11124,"[{'cast_id': 7, 'character': 'John McLoughlin'...","[{'credit_id': '538b02c00e0a2667020013bf', 'de...",1852,"[Nicolas Cage, Maria Bello, Maggie Gyllenhaal,...",[Oliver Stone]
13009,"[{'cast_id': 2, 'character': 'George W. Bush',...","[{'credit_id': '52fe437f9251416c75012bd7', 'de...",10523,"[Josh Brolin, Elizabeth Banks, Ellen Burstyn, ...",[Oliver Stone]
15829,"[{'cast_id': 8, 'character': 'Gordon Gekko', '...","[{'credit_id': '52fe45429251416c9102c3bf', 'de...",33909,"[Michael Douglas, Shia LaBeouf, Josh Brolin, C...",[Oliver Stone]
15997,"[{'cast_id': 1, 'character': 'Himself', 'credi...","[{'credit_id': '5961c92792514122510b02d4', 'de...",47426,"[Tariq Ali, Raúl Castro, Hugo Chávez, Cristina...",[Oliver Stone]
19151,"[{'cast_id': 52, 'character': 'Ophelia ""O"" Sag...","[{'credit_id': '52fe485a9251416c910894a1', 'de...",82525,"[Blake Lively, Taylor Kitsch, Aaron Taylor-Joh...",[Oliver Stone]
23145,"[{'cast_id': 6, 'character': 'Edmund Blackston...","[{'credit_id': '52fe45fec3a368484e07aa89', 'de...",29854,"[Jonathan Frid, Martine Beswick, Joseph Sirola...",[Oliver Stone]
24062,"[{'cast_id': 1, 'character': '', 'credit_id': ...","[{'credit_id': '54fa4ba39251413ab5000437', 'de...",329227,"[Hugo Chávez, Cristina Fernández de Kirchner, ...",[Oliver Stone]
34726,"[{'cast_id': 5, 'character': 'Narrator', 'cred...","[{'credit_id': '52fe4d539251416c751376a7', 'de...",189215,[Oliver Stone],[Oliver Stone]
38316,"[{'cast_id': 33, 'character': 'Edward Snowden'...","[{'credit_id': '54cd5be79251415cb8000d4a', 'de...",302401,"[Joseph Gordon-Levitt, Shailene Woodley, Melis...",[Oliver Stone]
44773,"[{'cast_id': 2, 'character': '', 'credit_id': ...","[{'credit_id': '5940daabc3a36803b401ccc1', 'de...",461805,"[Vladimir Putin, Oliver Stone]",[Oliver Stone]

In [19]:
dfc.head(2)

,cast,crew,id,actores,directores
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862,"[Tom Hanks, Tim Allen, Don Rickles, Jim Varney...",John Lasseter
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844,"[Robin Williams, Jonathan Hyde, Kirsten Dunst,...",[Joe Johnston]

In [20]:
dfc.drop(columns=['cast', 'crew'], inplace=True)

In [21]:
def remover_corchetes(lista):
    if isinstance(lista, list):
        return ', '.join(lista)  
    return lista

In [22]:
dfc['actores'].apply(remover_corchetes)

0        Tom Hanks, Tim Allen, Don Rickles, Jim Varney,...
1        Robin Williams, Jonathan Hyde, Kirsten Dunst, ...
2        Walter Matthau, Jack Lemmon, Ann-Margret, Soph...
3        Whitney Houston, Angela Bassett, Loretta Devin...
4        Steve Martin, Diane Keaton, Martin Short, Kimb...
                               ...
45471            Leila Hatami, Kourosh Tahami, Elham Korda
45472    Angel Aquino, Perry Dizon, Hazel Orencio, Joel...
45473    Erika Eleniak, Adam Baldwin, Julie du Page, Ja...
45474    Iwan Mosschuchin, Nathalie Lissenko, Pavel Pav...
45475
Name: actores, Length: 45476, dtype: object

In [23]:
dfc['directores'].apply(remover_corchetes)

0           John Lasseter
1            Joe Johnston
2           Howard Deutch
3         Forest Whitaker
4           Charles Shyer
               ...
45471    Hamid Nematollah
45472            Lav Diaz
45473      Mark L. Lester
45474    Yakov Protazanov
45475       Daisy Asquith
Name: directores, Length: 45476, dtype: object

In [24]:
# Guardo el dataset en un nuevo archivo csv.
dfc.to_csv('../credits_clean.csv', index=False)